// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package base

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Theming() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\n        :root {\n            --z-base: 0;\n            --z-overlay: 10;\n            --z-modal: 30;\n\n            --gray-400: #ced4da;\n        }\n\n        .page-wrapper {\n            height: 100vh;\n        }\n\n        .navbar-nav .nav-link {\n            --bs-nav-link-font-size: 1.6rem;\n            --bs-navbar-nav-link-padding-x: 1.4rem;\n        }\n\n        .form-floating {\n        }\n\n        .flex-basis-80 {\n            flex-basis: 80%;\n        }\n\n        .flex-basis-20 {\n            flex-basis: 20%;\n        }\n\n        p {\n            margin: 0 !important;\n        }\n\n\n        .figtree-bold {\n            font-family: \"Figtree\", sans-serif;\n            font-optical-sizing: auto;\n            font-weight: bold;\n            font-style: normal;\n        }\n\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
