// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auctions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAuction = `-- name: AddAuction :one
insert into auctions
(seller_id, category_id, product_name, product_desc, auc_mode, auc_status, starting_price, target_price, created_at)
values
($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, product_name, product_desc, auc_mode, auc_status, starting_price, target_price, created_at, category_id, seller_id
`

type AddAuctionParams struct {
	SellerID      pgtype.UUID      `json:"seller_id"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	ProductName   string           `json:"product_name"`
	ProductDesc   string           `json:"product_desc"`
	AucMode       AuctionMode      `json:"auc_mode"`
	AucStatus     AuctionStatus    `json:"auc_status"`
	StartingPrice float32          `json:"starting_price"`
	TargetPrice   pgtype.Float4    `json:"target_price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) AddAuction(ctx context.Context, arg AddAuctionParams) (Auction, error) {
	row := q.db.QueryRow(ctx, addAuction,
		arg.SellerID,
		arg.CategoryID,
		arg.ProductName,
		arg.ProductDesc,
		arg.AucMode,
		arg.AucStatus,
		arg.StartingPrice,
		arg.TargetPrice,
		arg.CreatedAt,
	)
	var i Auction
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.ProductDesc,
		&i.AucMode,
		&i.AucStatus,
		&i.StartingPrice,
		&i.TargetPrice,
		&i.CreatedAt,
		&i.CategoryID,
		&i.SellerID,
	)
	return i, err
}

const getAllAuctionsByUser = `-- name: GetAllAuctionsByUser :many
SELECT id, product_name, product_desc, auc_mode, auc_status, starting_price, target_price, created_at, seller_id, seller_name, seller_email, category_id, category_name FROM auction_details 
WHERE seller_id = $1
`

func (q *Queries) GetAllAuctionsByUser(ctx context.Context, sellerID pgtype.UUID) ([]AuctionDetail, error) {
	rows, err := q.db.Query(ctx, getAllAuctionsByUser, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuctionDetail{}
	for rows.Next() {
		var i AuctionDetail
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.ProductDesc,
			&i.AucMode,
			&i.AucStatus,
			&i.StartingPrice,
			&i.TargetPrice,
			&i.CreatedAt,
			&i.SellerID,
			&i.SellerName,
			&i.SellerEmail,
			&i.CategoryID,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuctionByName = `-- name: GetAuctionByName :one
SELECT id, product_name, product_desc, auc_mode, auc_status, starting_price, target_price, created_at, seller_id, seller_name, seller_email, category_id, category_name FROM auction_details
WHERE product_name = $1 LIMIT 1
`

func (q *Queries) GetAuctionByName(ctx context.Context, productName string) (AuctionDetail, error) {
	row := q.db.QueryRow(ctx, getAuctionByName, productName)
	var i AuctionDetail
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.ProductDesc,
		&i.AucMode,
		&i.AucStatus,
		&i.StartingPrice,
		&i.TargetPrice,
		&i.CreatedAt,
		&i.SellerID,
		&i.SellerName,
		&i.SellerEmail,
		&i.CategoryID,
		&i.CategoryName,
	)
	return i, err
}

const getAuctions = `-- name: GetAuctions :many
SELECT id, product_name, product_desc, auc_mode, auc_status, starting_price, target_price, created_at, seller_id, seller_name, seller_email, category_id, category_name, COUNT(*) OVER() AS TotalRows FROM auction_details WHERE
(($1::text IS NULL OR product_name LIKE '%' || $1::text || '%') OR
($2::text IS NULL OR product_desc LIKE '%' || $2::text || '%')) AND
(category_name = $3::text OR $3 IS NULL)
ORDER BY
    -- Sorting for product_name
    CASE WHEN $4 = 'product_name' AND NOT $5 THEN product_name END ASC,
    CASE WHEN $4 = 'product_name' AND $5 THEN product_name END DESC,

    -- Sorting for created_at
    CASE WHEN $4 = 'created_at' AND NOT $5 THEN created_at END ASC,
    CASE WHEN $4 = 'created_at' AND $5 THEN created_at END DESC
LIMIT $7 OFFSET $6
`

type GetAuctionsParams struct {
	ProductName  pgtype.Text `json:"product_name"`
	ProductDesc  pgtype.Text `json:"product_desc"`
	CategoryName pgtype.Text `json:"category_name"`
	OrderBy      interface{} `json:"order_by"`
	Reverse      interface{} `json:"reverse"`
	SkippedItems int32       `json:"skipped_items"`
	PageSize     int32       `json:"page_size"`
}

type GetAuctionsRow struct {
	ID            pgtype.UUID      `json:"id"`
	ProductName   string           `json:"product_name"`
	ProductDesc   string           `json:"product_desc"`
	AucMode       AuctionMode      `json:"auc_mode"`
	AucStatus     AuctionStatus    `json:"auc_status"`
	StartingPrice float32          `json:"starting_price"`
	TargetPrice   pgtype.Float4    `json:"target_price"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	SellerID      pgtype.UUID      `json:"seller_id"`
	SellerName    string           `json:"seller_name"`
	SellerEmail   string           `json:"seller_email"`
	CategoryID    pgtype.UUID      `json:"category_id"`
	CategoryName  string           `json:"category_name"`
	Totalrows     int64            `json:"totalrows"`
}

// TODO: Pretty sure there's SQL injection in that LIKE....
// limit and offset are NOT good for pagination, but let's ignore that for now
func (q *Queries) GetAuctions(ctx context.Context, arg GetAuctionsParams) ([]GetAuctionsRow, error) {
	rows, err := q.db.Query(ctx, getAuctions,
		arg.ProductName,
		arg.ProductDesc,
		arg.CategoryName,
		arg.OrderBy,
		arg.Reverse,
		arg.SkippedItems,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuctionsRow{}
	for rows.Next() {
		var i GetAuctionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.ProductDesc,
			&i.AucMode,
			&i.AucStatus,
			&i.StartingPrice,
			&i.TargetPrice,
			&i.CreatedAt,
			&i.SellerID,
			&i.SellerName,
			&i.SellerEmail,
			&i.CategoryID,
			&i.CategoryName,
			&i.Totalrows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
